Added postprocessing visualization example.
ansys/ansys-tools-visualization-interface pull request #112
Opened 2024-07-26 15:34 UTC by abhishekchitwar

Example to showcase the postprocessing with Ansys Flagship Simulations Results. (VTK is generated using pydpf-core).

2024-07-29 06:15 UTC, RobPasMue requested changes

2024-07-29 06:15 UTC, RobPasMue commented on examples/01-advanced-pyansys-examples/using_meshobject_with_field_data.py
> +======================================================================
```suggestion
====================================================================
Postprocessing simulation results using the ``MeshObjectPlot`` class
====================================================================
```

2024-07-29 06:15 UTC, RobPasMue commented on examples/01-advanced-pyansys-examples/using_meshobject_with_field_data.py
> +# =================================================
```suggestion
# Necessary imports
# =================
```

2024-07-29 06:15 UTC, RobPasMue commented on examples/01-advanced-pyansys-examples/using_meshobject_with_field_data.py
> +from ansys.fluent.core import examples
```suggestion
from ansys.fluent.core import examples
import pyvista as pv

from ansys.tools.visualization_interface.backends.pyvista import PyVistaBackend
from ansys.tools.visualization_interface import MeshObjectPlot, Plotter
```

2024-07-29 06:15 UTC, RobPasMue commented on examples/01-advanced-pyansys-examples/using_meshobject_with_field_data.py
> +# =================================================
```suggestion
# Download the VTK file
# =====================
```

2024-07-29 06:15 UTC, RobPasMue commented on examples/01-advanced-pyansys-examples/using_meshobject_with_field_data.py
> +# for Ansys Flagship products simulations results file format.
```suggestion
#
# A VTK dataset can be produced utilizing `PyDPF <https://dpf.docs.pyansys.com/version/stable/>`_
# for Ansys Flagship products simulations results file format.
```

2024-07-29 06:15 UTC, RobPasMue commented on examples/01-advanced-pyansys-examples/using_meshobject_with_field_data.py
> +# and a name or ID.
```suggestion
###################################################
# Define a custom object class
# ============================
#
# Note that the ``CustomObject`` class must have a way to get the mesh
# and a name or ID.
```

2024-07-29 06:15 UTC, RobPasMue commented on examples/01-advanced-pyansys-examples/using_meshobject_with_field_data.py
> +# ==================================================================
```suggestion
########################################################################
# Plot the ``MeshObjectPlot`` instance with mesh object & field data (0)
# ======================================================================
```

2024-07-29 06:15 UTC, RobPasMue commented on examples/01-advanced-pyansys-examples/using_meshobject_with_field_data.py
> +# ========================================================================
```suggestion
##############################################################################
# Plot the ``MeshObjectPlot`` instance with mesh object & other field data (1)
# ============================================================================
```

2024-07-29 08:29 UTC, AlejandroFernandezLuces commented
Thanks for adding this example @abhishekchitwar 🙂 

I'm a bit worried about having the fluent dependency in this repo. I believe it might cause dependency issues if we integrate this repo into fluent. Is it possible to include the required example directly in this repository? If not, that's fine, we can always revisit this if PyFluent incorporates this tool.

2024-07-29 08:33 UTC, RobPasMue commented
> I'm a bit worried about having the fluent dependency in this repo. I believe it might cause dependency issues if we integrate this repo into fluent. Is it possible to include the required example files directly in this repository? If not, that's fine, we can always revisit this if PyFluent incorporates this tool.

Well, since it is inside the ``docs`` target I wouldn't worry much about it. People will install the package only, or other additional targets. But the ``docs`` target is explicitly for building the documentation of this project.

2024-07-29 08:35 UTC, RobPasMue approved these changes

2024-07-29 08:35 UTC, merged

2024-07-29 08:36 UTC, RobPasMue commented
Looks like automerge was activated by @abhishekchitwar - sorry @AlejandroFernandezLuces, should have let it up to you to merge. I didn't see that automerge was active

2024-07-29 08:37 UTC, abhishekchitwar commented
@AlejandroFernandezLuces,

Thank you! This issue can be resolved by incorporating a download API in this library to facilitate downloading sample data from the PyAnsys example-data repository. There are no direct dependencies of Fluent apart from downloading example data.

2024-07-29 08:40 UTC, AlejandroFernandezLuces commented
> Looks like automerge was activated by @abhishekchitwar - sorry @AlejandroFernandezLuces, should have let it up to you to merge. I didn't see that automerge was active

No worries, it's good to go from my side 🙂

2024-07-29 08:43 UTC, AlejandroFernandezLuces commented
> @AlejandroFernandezLuces,
> 
> Thank you! This issue can be resolved by incorporating a download API in this library to facilitate downloading sample data from the PyAnsys example-data repository. There are no direct dependencies of Fluent apart from downloading example data.

We can do that if we have any conflicts with fluent at some point. For now let's keep it simple, thanks gain for adding the example 🚀

2024-07-29 21:15 UTC, ahernsean commented
@abhishekchitwar, do note that this dataset has the bug that VTK still considers the mesh cells to be invalid. The values in these cells ought to be zero, not 0x34.
![image](https://github.com/user-attachments/assets/93b9a4f0-3469-4d6f-a27a-c612b43142de)

2024-07-30 05:59 UTC, RobPasMue commented
Is this bug coming from PyVista @ahernsean? Or is it because the VTK file has that invalid info?

2024-07-30 12:15 UTC, abhishekchitwar commented
@ahernsean,
I attempted an alternative approach (converting from CGNS to VTK), but I still did not obtain any valid cells. The state described in the VTK documentation is not clear, as it includes:
```
    Valid = 0x0,
    WrongNumberOfPoints = 0x01,
    IntersectingEdges = 0x02,
    IntersectingFaces = 0x04,
    NoncontiguousEdges = 0x08,
    Nonconvex = 0x10,
    FacesAreOrientedIncorrectly = 0x20,
```
The number from the previous snapshot shared by you or the one below suggests that the issue is related to FacesAreOrientedIncorrectly, as we previously discussed. Any suggestions!

![image](https://github.com/user-attachments/assets/9a8d8c8f-71ac-404d-900c-4a72b78cb478)

2024-07-30 12:39 UTC, ahernsean commented
@RobPasMue, yes, I believe DPF is likely orienting the faces of polyhedra incorrectly in some cases. @abhishekchitwar and I were working with Paul Profizi on this, who said he'd try a few things and get back to us.

2024-07-30 12:42 UTC, ahernsean commented
> The state described in the VTK documentation is not clear, as it includes:
> 
> ```
>     Valid = 0x0,
>     WrongNumberOfPoints = 0x01,
>     IntersectingEdges = 0x02,
>     IntersectingFaces = 0x04,
>     NoncontiguousEdges = 0x08,
>     Nonconvex = 0x10,
>     FacesAreOrientedIncorrectly = 0x20,
> ```

The mapping is clear. Your image suggests that the majority of your cells have a ValidityState of 48 (dec), which is 30 (hex). This corresponds to NoncontiguousEdges and Nonconvex. Precisely what that means about the input mesh is less clear. I would want to restrict down to one or two cells to see what might be happening.